services:
  postgres:
    image: postgres:16-alpine
    container_name: nexus-postgres
    environment:
      POSTGRES_USER: nexus_owner
      POSTGRES_PASSWORD: nexus_owner
      POSTGRES_DB: nexus
    ports:
      - "5432:5432"
    volumes:
      - nexus_pg:/var/lib/postgresql/data
      - ./init-app-role.sql:/docker-entrypoint-initdb.d/10-init-app-role.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexus_owner -d nexus"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: nexus-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: nexus-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: nexus
      RABBITMQ_DEFAULT_PASS: nexus
    ports:
      - "5672:5672"
      - "15672:15672"   # consola de administración

volumes:
  nexus_pg:
